name: 'update docker pull'
description: 'notifies server to pull docker image'
author: 'bsdlp'
inputs: 
  image:
    description: 'docker image'
    required: true
  server_url:
    description: 'twirp server base url'
    required: true
  private_key:
    description: 'used to sign the request'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.server_url }}
    - ${{ inputs.image }}
    - ${{ inputs.private_key }}